### ISSUE TITLE
How to add same upload local file functionality to the image button in the command bar

### ISSUE THREAD

**Issue by BradyEdgar94** [nubasedev/react-mde#312]
First, let me say this is an amazing package :)

I have one issue I can't seem to sort out. When the user clicks the image button in the top toolbar, I want it to open the file finder on my computer, just like how it does when I drag & drop or click on the button upload bar. I understand the functionality regarding allowing the user to enter their own URL but for me, I need it to just always be local files the user uploads from their computer, even when they click on the image button in the toolbar.

How can I achieve this, do I need to remove the image button and make a custom one, or is there a better way?

Thanks!

**Comment by jaddoescad** [comment]
Any luck with this?

**Comment by gabrielmlinassi** [comment]
Just for reference, this is my solution for V.12.*

```
// First add a hidden input type=file somewhere. then when user clicks the upload image button, this code is executed:

function uploadImage() {
    if (uploadImgRef.current) {
      uploadImgRef.current.click()
    }
 }
```

```
// When user chooses the image:

async function uploadImageChange(e: React.ChangeEvent<HTMLInputElement>) {
    if (!e.target.files) return
    const file = e.target.files[0]

    try {
      await commandController.executeCommand('image')
      const state = textController.getState()
      
      const response = await uploadImgToS3(file)      
      if (response) {
        const { start, end } = state.selection
        textController.setSelectionRange({ start, end })
        textController.replaceSelection(response.url)
      }
    } catch (error) {
      toast.error('An error happened while uploading image to S3')
    }
  }
```
