### ISSUE TITLE
Automatic Height

### ISSUE THREAD

**Issue by Rendydendimara** [nubasedev/react-mde#317]
I have a problem writing the text, in short I want to write a long message with a high textarea that will fit the existing text. My question is, How do I make the height of the textarea auto so that I don't get distracted reading long text by scrolling. Thanks

**Comment by kmvan** [comment]
Have a look: https://github.com/andrerpena/react-mde/issues/306#issuecomment-819541008

**Comment by Waingapucoder** [comment]
Thank you friend, very helpful ^_^
